#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

if ! command -v "ruby" &>/dev/null; then
  dokku_log_fail "Missing ruby, install it (typically with sudo apt-get install ruby)"
fi

echo "Running dokku-cf-tunnel-update Ruby script"
ruby /var/lib/dokku/plugins/enabled/cf-tunnel-update/dokku-cf-tunnel-update.rb
